services:
  gazetteer:
    image: ghcr.io/dainst/gazetteer:${IMAGE}
    container_name: gazetteer
    depends_on:
      mongodb:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    environment:
      - CLUSTER_NAME=elasticsearch
      - CLUSTER_PORT=9200
      - MONGOREPLICASET=mongodb
      - SMTPHOST
      - SMTPPORT
      - SENDERMAIL
      - MAILUSERNAME
      - MAILPASSWORD
      - NOTIFICATIONMAIL
      - BASEURI=https://${HOST}/
    networks:
      - gazetteer
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.gazetteer-header.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.gazetteer-header.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.gazetteer-header.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.gazetteer-header.headers.accesscontrolmaxage=100"
      - "traefik.http.routers.gazetteer-router.rule=Host(`${HOST}`)"
      - "traefik.http.routers.gazetteer-router.entrypoints=websecure"
      - "traefik.http.routers.gazetteer-router.tls=true"
      - "traefik.http.routers.gazetteer-router.tls.certresolver=dfn"
      - "traefik.http.routers.gazetteer-router.middlewares=gazetteer-header"
      - "traefik.http.services.gazetteer-service.loadbalancer.server.port=8080"

  mongodb:
    container_name: mongodb
    image: mongo:8
    volumes:
      - ./.mongo-data/:/data/db
    environment:
      MONGO_INITDB_DATABASE: gazetteer
    ports:
      - 27017:27017
    networks:
      - gazetteer
    restart: always
    labels:
      - "traefik.enable=false"

  elasticsearch:
    container_name: elasticsearch
    image: ghcr.io/dainst/gazetteer-elasticsearch:latest
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - cluster.name=gazetteer
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-o",
          "/dev/null",
          "-s",
          "--head",
          "--fail",
          "localhost:9200",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    user: 1000:1000
    volumes:
      - ./.es-data:/usr/share/elasticsearch/data
    networks:
      - gazetteer
    restart: always
    labels:
      - "traefik.enable=false"

  traefik:
    image: traefik:v3.6
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
      - ./traefik/config.yml:/etc/traefik/traefik.yml
    networks:
      - gazetteer
    restart: always

networks:
  gazetteer:
    name: gazetteer
